import dayjs from 'dayjs';

const amoreMallUrl = (id: number) => `https://www.amoremall.com/kr/ko/product/detail?pid=${id}`;

export const personaBaseRaw: Array<Record<string, unknown>> = [
  {
    personaId: 'p-001',
    persona: '바쁜 워커홀릭 20대 여성',
    ageGroup: '20대',
    mainCategory: '스킨케어',
    purchaseMethod: '빠른 구매(딥링크 선호)',
    brandLoyalty: '중~상',
    trendKeywords: ['5분 루틴', '보습', '출근'],
    coreKeywords: ['간편', '수분', '시간 절약'],
    priceSensitivity: '중',
    benefitSensitivity: '상',
  },
  {
    personaId: 'p-002',
    persona: '피부 컨디션 민감한 30대 남성',
    ageGroup: '30대',
    mainCategory: '남성 스킨케어',
    purchaseMethod: '정기/재구매',
    brandLoyalty: '상',
    trendKeywords: ['미니멀', '진정', '올인원'],
    coreKeywords: ['간편', '저자극', '리차징'],
    priceSensitivity: '중',
    benefitSensitivity: '중',
  },
  {
    personaId: 'p-003',
    persona: '트렌드에 민감한 20대',
    ageGroup: '20대',
    mainCategory: '메이크업',
    purchaseMethod: '신상/한정판 즉시 구매',
    brandLoyalty: '중',
    trendKeywords: ['홀리데이', '한정판', '신상'],
    coreKeywords: ['선점', '컬러', '바이럴'],
    priceSensitivity: '하',
    benefitSensitivity: '중',
  },
  {
    personaId: 'p-004',
    persona: '가성비 중시 20대 직장인',
    ageGroup: '20대',
    mainCategory: '기초',
    purchaseMethod: '쿠폰/적립금 기반',
    brandLoyalty: '중',
    trendKeywords: ['쿠폰', '점심시간', '가성비'],
    coreKeywords: ['할인', '혜택', '빠른 결정'],
    priceSensitivity: '상',
    benefitSensitivity: '상',
  },
  {
    personaId: 'p-005',
    persona: '모공/피지 고민 20대',
    ageGroup: '20대',
    mainCategory: '클렌징/마스크',
    purchaseMethod: '리뷰/성분 확인 후 구매',
    brandLoyalty: '중',
    trendKeywords: ['클린 뷰티', '모공', '피지'],
    coreKeywords: ['딥클렌징', '정리', '주말'],
    priceSensitivity: '중',
    benefitSensitivity: '중',
  },
  {
    personaId: 'p-006',
    persona: '퇴근 후 홈케어 루틴러 30대',
    ageGroup: '30대',
    mainCategory: '앰플/홈케어',
    purchaseMethod: '세트/라인 구매',
    brandLoyalty: '상',
    trendKeywords: ['홈케어', '앰플', '루틴'],
    coreKeywords: ['컨디션', '탄력', '마무리'],
    priceSensitivity: '중',
    benefitSensitivity: '중',
  },
];

export const buildTrendRowsRaw = (todayStr: string): Array<Record<string, unknown>> => {
  const d1 = dayjs(todayStr).subtract(1, 'day').format('YYYY-MM-DD');
  const d2 = dayjs(todayStr).subtract(2, 'day').format('YYYY-MM-DD');
  return [
    {
      id: 2001,
      personaId: 'p-001',
      persona: '바쁜 워커홀릭 20대 여성',
      date: d1,
      time: '09:00',
      channel: '푸시',
      recipientCount: 1280,
      product: '라네즈 워터뱅크 블루 히알루로닉 크림',
      productUrl: amoreMallUrl(2001),
      title: '출근 전 5분 보습 루틴',
      description: '출근 준비로 바쁘죠? 5분 보습 루틴으로 촉촉하게 시작해요. 혜택 확인하기',
      recommendedReason: '출근 전 5분 루틴 니즈가 반복적으로 관측됨',
      status: 'success',
      successCount: 128,
      errorCount: 0,
      optoutCount: 0,
      failedRecipients: [],
    },
    {
      id: 2002,
      personaId: 'p-002',
      persona: '피부 컨디션 민감한 30대 남성',
      date: d1,
      time: '10:30',
      channel: '카카오톡 알림톡',
      recipientCount: 100,
      product: '아이오페 맨 올인원 리차징 로션',
      productUrl: amoreMallUrl(2002),
      title: '간편한 올인원으로 루틴 끝',
      description: '번들거림은 줄이고 수분은 채우는 올인원. 상품 상세 보기',
      recommendedReason: '피부 민감군에서 올인원 카테고리 선호도가 높음',
      status: 'error',
      successCount: 94,
      errorCount: 6,
      optoutCount: 0,
      failedRecipients: [
        { userId: 'u-10001', name: '김민수', failureType: 'error', failureMessage: '전송 API 오류' },
        { userId: 'u-10002', name: '박지훈', failureType: 'error', failureMessage: '전송 API 오류' },
        { userId: 'u-10003', name: '이서연', failureType: 'error', failureMessage: '전송 API 오류' },
        { userId: 'u-10004', name: '정하늘', failureType: 'error', failureMessage: '전송 API 오류' },
        { userId: 'u-10005', name: '오지은', failureType: 'error', failureMessage: '전송 API 오류' },
        { userId: 'u-10006', name: '최도윤', failureType: 'error', failureMessage: '전송 API 오류' },
      ],
    },
    {
      id: 2003,
      personaId: 'p-003',
      persona: '트렌드에 민감한 20대',
      date: d2,
      time: '11:00',
      channel: '푸시',
      recipientCount: 2100,
      product: '헤라 센슈얼 누드 글로스 (홀리데이 컬러)',
      productUrl: amoreMallUrl(2003),
      title: '홀리데이 한정 컬러, 품절 전 선점',
      description: '지금 가장 핫한 홀리데이 컬러, 품절 전 확인!',
      recommendedReason: '한정판/신상 메시지의 반응도가 높은 그룹',
      status: 'success',
      successCount: 210,
      errorCount: 0,
      optoutCount: 0,
      failedRecipients: [],
    },
    {
      id: 2004,
      personaId: 'p-004',
      persona: '가성비 중시 20대 직장인',
      date: d2,
      time: '12:00',
      channel: '카카오톡 알림톡',
      recipientCount: 172,
      product: '이니스프리 그린티 씨드 세럼',
      productUrl: amoreMallUrl(2004),
      title: '점심시간 10분 쇼핑 찬스',
      description: '쿠폰 적용 가능한 대표 보습 세럼',
      recommendedReason: '혜택 민감군에서 점심시간 타임세일 메시지 반응이 높음',
      status: 'error',
      successCount: 160,
      errorCount: 0,
      optoutCount: 12,
      failedRecipients: [
        { userId: 'u-20001', name: '홍길동', failureType: 'optout', failureMessage: '수신 거부' },
        { userId: 'u-20002', name: '장미', failureType: 'optout', failureMessage: '수신 거부' },
        { userId: 'u-20003', name: '윤아', failureType: 'optout', failureMessage: '수신 거부' },
        { userId: 'u-20004', name: '한지민', failureType: 'optout', failureMessage: '수신 거부' },
        { userId: 'u-20005', name: '강호동', failureType: 'optout', failureMessage: '수신 거부' },
      ],
    },
    // 오늘자(추이에서도 확인 가능)
    {
      id: 2010,
      personaId: 'p-006',
      persona: '퇴근 후 홈케어 루틴러 30대',
      date: todayStr,
      time: '20:30',
      channel: '푸시',
      recipientCount: 1800,
      product: '아이오페 슈퍼바이탈 앰플',
      productUrl: amoreMallUrl(2010),
      title: '퇴근 후 1단계 앰플 루틴',
      description: '오늘 하루 고생했어요. 퇴근 후 1단계 앰플로 탄탄한 컨디션을 채워보세요',
      recommendedReason: '홈케어 루틴러에게 “퇴근 후” 타이밍 메시지 반응이 안정적',
      status: 'success',
      successCount: 180,
      errorCount: 0,
      optoutCount: 0,
      failedRecipients: [],
    },
    // 아래는 상태 3종(success/error/info) UI 확인용 케이스들
    {
      id: 2011,
      personaId: 'p-001',
      persona: '바쁜 워커홀릭 20대 여성',
      date: todayStr,
      time: '23:50',
      channel: '카카오톡 알림톡',
      recipientCount: 320,
      product: '라네즈 워터뱅크 블루 히알루로닉 크림',
      productUrl: amoreMallUrl(2011),
      title: '오늘은 발송 예정(테스트)',
      description: 'info 상태(발송 예정) UI 확인용 데이터입니다.',
      recommendedReason: 'UI 상태칩/필터 옵션 확인 목적',
      status: 'info',
      successCount: 0,
      errorCount: 0,
      optoutCount: 0,
      failedRecipients: [],
    },
    {
      id: 2012,
      personaId: 'p-002',
      persona: '피부 컨디션 민감한 30대 남성',
      date: todayStr,
      time: '23:55',
      channel: '푸시',
      recipientCount: 250,
      product: '아이오페 맨 올인원 리차징 로션',
      productUrl: amoreMallUrl(2012),
      title: '발송 예정(시간 변경 테스트)',
      description: 'info 상태(발송 예정) + 상세 드로어 시간 변경 UI 확인용 데이터입니다.',
      recommendedReason: 'UI 상태칩/필터 옵션 확인 목적',
      status: 'info',
      successCount: 0,
      errorCount: 0,
      optoutCount: 0,
      failedRecipients: [],
    },
    {
      id: 2013,
      personaId: 'p-004',
      persona: '가성비 중시 20대 직장인',
      date: todayStr,
      time: '19:20',
      channel: '카카오톡 알림톡',
      recipientCount: 80,
      product: '이니스프리 그린티 씨드 세럼',
      productUrl: amoreMallUrl(2013),
      title: '발송 취소 케이스(테스트)',
      description: 'error 상태(발송 취소) UI 확인용 데이터입니다.',
      recommendedReason: 'UI 상태칩/필터 옵션 확인 목적',
      status: 'error',
      successCount: 0,
      errorCount: 0,
      optoutCount: 0,
      failedRecipients: [],
    },
  ];
};


